#ifndef SRV_TASK_MANAGER_H
#define SRV_TASK_MANAGER_H

#define COMMAND_HANDLER_TASK_REC_MS 200
#define MOTOR_CONTROL_TASK_REC_MS 100
#define SERIAL_REPORT_TASK_REC_MS 200

#define TRAFFIC_CONTROL_TASK_REC_MS 50
#define REQUEST_NORTH_SOUTH_TASK_REC_MS 100
#define NIGHT_MODE_TOGGLE_TASK_REC_MS 50
#define NIGHT_BLINKING_TASK_REC_MS 500

#define TRAFFIC_CONTROL_TASK_STACK_SIZE 256
#define REQUEST_NORTH_SOUTH_TASK_STACK_SIZE 256
#define NIGHT_MODE_TOGGLE_TASK_STACK_SIZE 256
#define NIGHT_BLINKING_TASK_STACK_SIZE 256

#define TRAFFIC_CONTROL_TASK_PRIORITY 2
#define REQUEST_NORTH_SOUTH_TASK_PRIORITY 1
#define NIGHT_MODE_TOGGLE_TASK_PRIORITY 1
#define NIGHT_BLINKING_TASK_PRIORITY 1

void trafficControlTask(void* pvParameters);
void requestNorthSouthTask(void *pvParameters);
void nightModeToggleTask(void* pvParameters);
void nightBlinkingTask(void* pvParameters);

#endif