#include "srv_fsm.h"

const FSMState FSMStatesStruct[] = {
    { eastWestToGreen, EAST_WEST_GREEN_TIME, {STATE_EAST_WEST_GREEN, STATE_EAST_WEST_YELLOW, STATE_EAST_WEST_GREEN, STATE_EAST_WEST_YELLOW} },
    { eastWestToYellow, EAST_WEST_YELLOW_TIME, {STATE_NORTH_SOUTH_ENTRY_YELLOW, STATE_NORTH_SOUTH_ENTRY_YELLOW, STATE_NORTH_SOUTH_ENTRY_YELLOW, STATE_NORTH_SOUTH_ENTRY_YELLOW} },
    { northSouthRedToYellow, NORTH_SOUTH_ENTRY_YELLOW_TIME, {STATE_NORTH_SOUTH_GREEN, STATE_NORTH_SOUTH_GREEN, STATE_NORTH_SOUTH_GREEN, STATE_NORTH_SOUTH_GREEN} },
    { northSouthToGreen, NORTH_SOUTH_GREEN_TIME, {STATE_NORTH_SOUTH_GREEN, STATE_NORTH_SOUTH_YELLOW, STATE_NORTH_SOUTH_GREEN, STATE_NORTH_SOUTH_YELLOW} },
    { northSouthToYellow, NORTH_SOUTH_YELLOW_TIME, {STATE_EAST_WEST_ENTRY_YELLOW, STATE_EAST_WEST_ENTRY_YELLOW, STATE_EAST_WEST_ENTRY_YELLOW, STATE_EAST_WEST_ENTRY_YELLOW} },
    { eastWestRedToYellow, EAST_WEST_ENTRY_YELLOW_TIME, {STATE_EAST_WEST_GREEN, STATE_EAST_WEST_GREEN, STATE_EAST_WEST_GREEN, STATE_EAST_WEST_GREEN} }
};
